apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: simplest
  namespace: spring-petclinic
spec:
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    processors:
    
    exporters:
      logging:    
        loglevel: debug
    
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: []
          exporters: [logging]
