apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: simplest
  namespace: spring-petclinic
spec:
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    processors:
    
    exporters:
      logging:    
        loglevel: debug
      zipkin:
        endpoint: "http://zipkin.istio-system.svc.cluster.local:9411/api/v2/spans"

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: []
          exporters: [logging,zipkin]
